[dependencies]
bitfield = '>=0.13'
bytes = '>=0.4'
chrono = '>=0.4.0'
etherparse = '>=0.6'
interfaces = '>=0.0.4'
pcap = '>=0.7'
serde_yaml = '>=0.8'
tokio = '>=0.1'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
name = 'gp_daq'
version = '0.1.0'
